### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by cmyplay** [mateuuszzzzz/applemusicpy#1]
I'm new to Python, but I'm learning quickly. I'm astounded by how empowering this all is when I understand how it works. And these bindings are so great, thank you.

1. It would be amazing to see some details about how to use the calls.
It looks as if you've included calls to a user's library but it's difficult to see how.

2. With the expanded capabilities Apple revealed at WWDC22 this week, have you got any plans to implement an update?

**Comment by mateuuszzzzz** [comment]
Hi! At the beginning I would like to apologize for delay. I had health
issues and vacations in the meantime. I appreciate your mail.

Currently I’m working on project on my university and have full time job.
This means I don’t have a lot of time to develop applemusicpy.

I would like to make documentation in the future but as I said before I
have lack of time.

Also If you still interested I can explain you how calls work

Best regards,
Mateusz.

W dniu piątek, 10 czerwca 2022 cmyplay ***@***.***>
napisał(a):

**Comment by mateuuszzzzz** [comment]
Also I want to implement update related to WWDC22

W dniu piątek, 10 czerwca 2022 cmyplay ***@***.***>
napisał(a):
